name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest --cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
