name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest --cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
