name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest --cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
